version: '3.9'

services:
  app:
    container_name: 'sandbox'
    build: .
    ports:
      - '8085:8085'
    depends_on:
      - cache
      - clickhouse

  cache:
    container_name: 'redis-sandbox'
    image: redis:7.2.4-alpine
    restart: always
    ports:
      - '6379:6379'

  clickhouse:
    image: yandex/clickhouse-server
    container_name: 'clickhouse-sandbox'
    ports:
      - "8123:8123"
      - "9002:9000"
      - "9003:9001"
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - ./config:/etc/clickhouse-server/config
      - ./users:/etc/clickhouse-server/users

  zookeeper:
    platform: linux/x86_64
    image: confluentinc/cp-zookeeper:7.3.2
    hostname: zoo1
    container_name: zoo1
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_SERVERS: zoo1:2888:3888

  kafka:
    platform: linux/x86_64
    image: confluentinc/cp-kafka:7.3.2
    hostname: kafka1
    container_name: kafka1
    ports:
      - "9092:9092" # Порт для клиентов
      - "19092:19092" # Порт для внутренних брокеров
    environment:
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:19092,EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_JMX_PORT: 9999
      KAFKA_JMX_HOSTNAME: localhost
      KAFKA_AUTHORIZER_CLASS_NAME: kafka.security.authorizer.AclAuthorizer
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "true"
    depends_on:
      - zookeeper

  akhq:
    platform: linux/x86_64
    image: tchiotludo/akhq
    container_name: akhq
    ports:
      - "8086:8080" # Порт для доступа к интерфейсу
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            kafka-cluster:
              properties:
                bootstrap.servers: "kafka:19092"
                security.protocol: PLAINTEXT
    depends_on:
      - kafka

volumes:
  clickhouse_data:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local