# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import application.clients.grpc.account_proxy.account_proxy_pb2 as account__proxy__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

GRPC_GENERATED_VERSION = '1.66.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in account_proxy_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AccountServiceProxyStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Login = channel.unary_unary(
                '/account_proxy.AccountServiceProxy/Login',
                request_serializer=account__proxy__pb2.LoginRequest.SerializeToString,
                response_deserializer=account__proxy__pb2.LoginResponse.FromString,
                _registered_method=True)
        self.Logout = channel.unary_unary(
                '/account_proxy.AccountServiceProxy/Logout',
                request_serializer=account__proxy__pb2.LogoutRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.LogoutAll = channel.unary_unary(
                '/account_proxy.AccountServiceProxy/LogoutAll',
                request_serializer=account__proxy__pb2.LogoutAllRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.GetCurrentAccount = channel.unary_unary(
                '/account_proxy.AccountServiceProxy/GetCurrentAccount',
                request_serializer=account__proxy__pb2.GetCurrentAccountRequest.SerializeToString,
                response_deserializer=account__proxy__pb2.GetCurrentAccountResponse.FromString,
                _registered_method=True)
        self.GetAccounts = channel.unary_unary(
                '/account_proxy.AccountServiceProxy/GetAccounts',
                request_serializer=account__proxy__pb2.GetAccountsRequest.SerializeToString,
                response_deserializer=account__proxy__pb2.GetAccountsResponse.FromString,
                _registered_method=True)
        self.RegisterAccount = channel.unary_unary(
                '/account_proxy.AccountServiceProxy/RegisterAccount',
                request_serializer=account__proxy__pb2.RegisterAccountRequest.SerializeToString,
                response_deserializer=account__proxy__pb2.RegisterAccountResponse.FromString,
                _registered_method=True)
        self.ActivateAccount = channel.unary_unary(
                '/account_proxy.AccountServiceProxy/ActivateAccount',
                request_serializer=account__proxy__pb2.ActivateAccountRequest.SerializeToString,
                response_deserializer=account__proxy__pb2.ActivateAccountResponse.FromString,
                _registered_method=True)
        self.ChangeAccountEmail = channel.unary_unary(
                '/account_proxy.AccountServiceProxy/ChangeAccountEmail',
                request_serializer=account__proxy__pb2.ChangeAccountEmailRequest.SerializeToString,
                response_deserializer=account__proxy__pb2.ChangeAccountEmailResponse.FromString,
                _registered_method=True)
        self.ResetAccountPassword = channel.unary_unary(
                '/account_proxy.AccountServiceProxy/ResetAccountPassword',
                request_serializer=account__proxy__pb2.ResetAccountPasswordRequest.SerializeToString,
                response_deserializer=account__proxy__pb2.ResetAccountPasswordResponse.FromString,
                _registered_method=True)
        self.ChangeAccountPassword = channel.unary_unary(
                '/account_proxy.AccountServiceProxy/ChangeAccountPassword',
                request_serializer=account__proxy__pb2.ChangeAccountPasswordRequest.SerializeToString,
                response_deserializer=account__proxy__pb2.ChangeAccountPasswordResponse.FromString,
                _registered_method=True)
        self.UpdateAccount = channel.unary_unary(
                '/account_proxy.AccountServiceProxy/UpdateAccount',
                request_serializer=account__proxy__pb2.UpdateAccountRequest.SerializeToString,
                response_deserializer=account__proxy__pb2.UpdateAccountResponse.FromString,
                _registered_method=True)
        self.RegisterAccountClientStream = channel.stream_unary(
                '/account_proxy.AccountServiceProxy/RegisterAccountClientStream',
                request_serializer=account__proxy__pb2.RegisterAccountRequest.SerializeToString,
                response_deserializer=account__proxy__pb2.RegisterAccountClientStreamResponse.FromString,
                _registered_method=True)
        self.GetAccountsServerStream = channel.unary_stream(
                '/account_proxy.AccountServiceProxy/GetAccountsServerStream',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=account__proxy__pb2.User.FromString,
                _registered_method=True)
        self.GetAccountsByLoginDuplexStream = channel.stream_stream(
                '/account_proxy.AccountServiceProxy/GetAccountsByLoginDuplexStream',
                request_serializer=account__proxy__pb2.GetAccountsByLoginRequest.SerializeToString,
                response_deserializer=account__proxy__pb2.GetAccountsByLoginResponse.FromString,
                _registered_method=True)


class AccountServiceProxyServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Login(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Logout(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LogoutAll(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCurrentAccount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAccounts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterAccount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ActivateAccount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ChangeAccountEmail(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResetAccountPassword(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ChangeAccountPassword(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateAccount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterAccountClientStream(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAccountsServerStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAccountsByLoginDuplexStream(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AccountServiceProxyServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Login': grpc.unary_unary_rpc_method_handler(
                    servicer.Login,
                    request_deserializer=account__proxy__pb2.LoginRequest.FromString,
                    response_serializer=account__proxy__pb2.LoginResponse.SerializeToString,
            ),
            'Logout': grpc.unary_unary_rpc_method_handler(
                    servicer.Logout,
                    request_deserializer=account__proxy__pb2.LogoutRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'LogoutAll': grpc.unary_unary_rpc_method_handler(
                    servicer.LogoutAll,
                    request_deserializer=account__proxy__pb2.LogoutAllRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'GetCurrentAccount': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCurrentAccount,
                    request_deserializer=account__proxy__pb2.GetCurrentAccountRequest.FromString,
                    response_serializer=account__proxy__pb2.GetCurrentAccountResponse.SerializeToString,
            ),
            'GetAccounts': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAccounts,
                    request_deserializer=account__proxy__pb2.GetAccountsRequest.FromString,
                    response_serializer=account__proxy__pb2.GetAccountsResponse.SerializeToString,
            ),
            'RegisterAccount': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterAccount,
                    request_deserializer=account__proxy__pb2.RegisterAccountRequest.FromString,
                    response_serializer=account__proxy__pb2.RegisterAccountResponse.SerializeToString,
            ),
            'ActivateAccount': grpc.unary_unary_rpc_method_handler(
                    servicer.ActivateAccount,
                    request_deserializer=account__proxy__pb2.ActivateAccountRequest.FromString,
                    response_serializer=account__proxy__pb2.ActivateAccountResponse.SerializeToString,
            ),
            'ChangeAccountEmail': grpc.unary_unary_rpc_method_handler(
                    servicer.ChangeAccountEmail,
                    request_deserializer=account__proxy__pb2.ChangeAccountEmailRequest.FromString,
                    response_serializer=account__proxy__pb2.ChangeAccountEmailResponse.SerializeToString,
            ),
            'ResetAccountPassword': grpc.unary_unary_rpc_method_handler(
                    servicer.ResetAccountPassword,
                    request_deserializer=account__proxy__pb2.ResetAccountPasswordRequest.FromString,
                    response_serializer=account__proxy__pb2.ResetAccountPasswordResponse.SerializeToString,
            ),
            'ChangeAccountPassword': grpc.unary_unary_rpc_method_handler(
                    servicer.ChangeAccountPassword,
                    request_deserializer=account__proxy__pb2.ChangeAccountPasswordRequest.FromString,
                    response_serializer=account__proxy__pb2.ChangeAccountPasswordResponse.SerializeToString,
            ),
            'UpdateAccount': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateAccount,
                    request_deserializer=account__proxy__pb2.UpdateAccountRequest.FromString,
                    response_serializer=account__proxy__pb2.UpdateAccountResponse.SerializeToString,
            ),
            'RegisterAccountClientStream': grpc.stream_unary_rpc_method_handler(
                    servicer.RegisterAccountClientStream,
                    request_deserializer=account__proxy__pb2.RegisterAccountRequest.FromString,
                    response_serializer=account__proxy__pb2.RegisterAccountClientStreamResponse.SerializeToString,
            ),
            'GetAccountsServerStream': grpc.unary_stream_rpc_method_handler(
                    servicer.GetAccountsServerStream,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=account__proxy__pb2.User.SerializeToString,
            ),
            'GetAccountsByLoginDuplexStream': grpc.stream_stream_rpc_method_handler(
                    servicer.GetAccountsByLoginDuplexStream,
                    request_deserializer=account__proxy__pb2.GetAccountsByLoginRequest.FromString,
                    response_serializer=account__proxy__pb2.GetAccountsByLoginResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'account_proxy.AccountServiceProxy', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('account_proxy.AccountServiceProxy', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AccountServiceProxy(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Login(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/account_proxy.AccountServiceProxy/Login',
            account__proxy__pb2.LoginRequest.SerializeToString,
            account__proxy__pb2.LoginResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Logout(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/account_proxy.AccountServiceProxy/Logout',
            account__proxy__pb2.LogoutRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LogoutAll(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/account_proxy.AccountServiceProxy/LogoutAll',
            account__proxy__pb2.LogoutAllRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCurrentAccount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/account_proxy.AccountServiceProxy/GetCurrentAccount',
            account__proxy__pb2.GetCurrentAccountRequest.SerializeToString,
            account__proxy__pb2.GetCurrentAccountResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAccounts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/account_proxy.AccountServiceProxy/GetAccounts',
            account__proxy__pb2.GetAccountsRequest.SerializeToString,
            account__proxy__pb2.GetAccountsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterAccount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/account_proxy.AccountServiceProxy/RegisterAccount',
            account__proxy__pb2.RegisterAccountRequest.SerializeToString,
            account__proxy__pb2.RegisterAccountResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ActivateAccount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/account_proxy.AccountServiceProxy/ActivateAccount',
            account__proxy__pb2.ActivateAccountRequest.SerializeToString,
            account__proxy__pb2.ActivateAccountResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ChangeAccountEmail(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/account_proxy.AccountServiceProxy/ChangeAccountEmail',
            account__proxy__pb2.ChangeAccountEmailRequest.SerializeToString,
            account__proxy__pb2.ChangeAccountEmailResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResetAccountPassword(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/account_proxy.AccountServiceProxy/ResetAccountPassword',
            account__proxy__pb2.ResetAccountPasswordRequest.SerializeToString,
            account__proxy__pb2.ResetAccountPasswordResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ChangeAccountPassword(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/account_proxy.AccountServiceProxy/ChangeAccountPassword',
            account__proxy__pb2.ChangeAccountPasswordRequest.SerializeToString,
            account__proxy__pb2.ChangeAccountPasswordResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateAccount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/account_proxy.AccountServiceProxy/UpdateAccount',
            account__proxy__pb2.UpdateAccountRequest.SerializeToString,
            account__proxy__pb2.UpdateAccountResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterAccountClientStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/account_proxy.AccountServiceProxy/RegisterAccountClientStream',
            account__proxy__pb2.RegisterAccountRequest.SerializeToString,
            account__proxy__pb2.RegisterAccountClientStreamResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAccountsServerStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/account_proxy.AccountServiceProxy/GetAccountsServerStream',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            account__proxy__pb2.User.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAccountsByLoginDuplexStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/account_proxy.AccountServiceProxy/GetAccountsByLoginDuplexStream',
            account__proxy__pb2.GetAccountsByLoginRequest.SerializeToString,
            account__proxy__pb2.GetAccountsByLoginResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
