"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from builtins import (
    bool,
    bytes,
    int,
    str,
)
from collections.abc import (
    Iterable,
    Mapping,
)
from google.protobuf.descriptor import (
    Descriptor,
    FileDescriptor,
)
from google.protobuf.internal.containers import (
    MessageMap,
    RepeatedScalarFieldContainer,
)
from google.protobuf.message import (
    Message,
)
from typing import (
    Literal,
    final,
)

DESCRIPTOR: FileDescriptor

@final
class KafkaMessage(Message):
    DESCRIPTOR: Descriptor

    TOPIC_FIELD_NUMBER: int
    VALUE_FIELD_NUMBER: int
    KEY_FIELD_NUMBER: int
    PARTITION_FIELD_NUMBER: int
    OFFSET_FIELD_NUMBER: int
    TIMESTAMP_MS_FIELD_NUMBER: int
    topic: str
    value: bytes
    key: str
    partition: int
    offset: int
    timestamp_ms: int
    def __init__(
        self,
        *,
        topic: str = ...,
        value: bytes = ...,
        key: str = ...,
        partition: int = ...,
        offset: int = ...,
        timestamp_ms: int = ...,
    ) -> None: ...
    def ClearField(self, field_name: Literal["key", b"key", "offset", b"offset", "partition", b"partition", "timestamp_ms", b"timestamp_ms", "topic", b"topic", "value", b"value"]) -> None: ...

@final
class RegisterEvent(Message):
    DESCRIPTOR: Descriptor

    LOGIN_FIELD_NUMBER: int
    EMAIL_FIELD_NUMBER: int
    PASSWORD_FIELD_NUMBER: int
    login: str
    email: str
    password: str
    def __init__(
        self,
        *,
        login: str = ...,
        email: str = ...,
        password: str = ...,
    ) -> None: ...
    def ClearField(self, field_name: Literal["email", b"email", "login", b"login", "password", b"password"]) -> None: ...

@final
class RegisterEventError(Message):
    DESCRIPTOR: Descriptor

    INPUT_DATA_FIELD_NUMBER: int
    ERROR_MESSAGE_FIELD_NUMBER: int
    ERROR_TYPE_FIELD_NUMBER: int
    error_type: str
    @property
    def input_data(self) -> RegisterEvent: ...
    @property
    def error_message(self) -> ErrorMessage: ...
    def __init__(
        self,
        *,
        input_data: RegisterEvent | None = ...,
        error_message: ErrorMessage | None = ...,
        error_type: str = ...,
    ) -> None: ...
    def HasField(self, field_name: Literal["error_message", b"error_message", "input_data", b"input_data"]) -> bool: ...
    def ClearField(self, field_name: Literal["error_message", b"error_message", "error_type", b"error_type", "input_data", b"input_data"]) -> None: ...

@final
class ErrorList(Message):
    DESCRIPTOR: Descriptor

    VALUES_FIELD_NUMBER: int
    @property
    def values(self) -> RepeatedScalarFieldContainer[str]: ...
    def __init__(
        self,
        *,
        values: Iterable[str] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: Literal["values", b"values"]) -> None: ...

@final
class ErrorMessage(Message):
    DESCRIPTOR: Descriptor

    @final
    class ErrorsEntry(Message):
        DESCRIPTOR: Descriptor

        KEY_FIELD_NUMBER: int
        VALUE_FIELD_NUMBER: int
        key: str
        @property
        def value(self) -> ErrorList: ...
        def __init__(
            self,
            *,
            key: str = ...,
            value: ErrorList | None = ...,
        ) -> None: ...
        def HasField(self, field_name: Literal["value", b"value"]) -> bool: ...
        def ClearField(self, field_name: Literal["key", b"key", "value", b"value"]) -> None: ...

    TYPE_FIELD_NUMBER: int
    TITLE_FIELD_NUMBER: int
    STATUS_FIELD_NUMBER: int
    TRACE_ID_FIELD_NUMBER: int
    ERRORS_FIELD_NUMBER: int
    type: str
    title: str
    status: int
    trace_id: str
    @property
    def errors(self) -> MessageMap[str, ErrorList]: ...
    def __init__(
        self,
        *,
        type: str = ...,
        title: str = ...,
        status: int = ...,
        trace_id: str = ...,
        errors: Mapping[str, ErrorList] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: Literal["errors", b"errors", "status", b"status", "title", b"title", "trace_id", b"trace_id", "type", b"type"]) -> None: ...
