# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: kafka.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'kafka.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bkafka.proto\x12\x05kafka\x1a\x1bgoogle/protobuf/empty.proto\"r\n\x0cKafkaMessage\x12\r\n\x05topic\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x0c\x12\x0b\n\x03key\x18\x03 \x01(\t\x12\x11\n\tpartition\x18\x04 \x01(\x05\x12\x0e\n\x06offset\x18\x05 \x01(\x03\x12\x14\n\x0ctimestamp_ms\x18\x06 \x01(\x03\"?\n\rRegisterEvent\x12\r\n\x05login\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x10\n\x08password\x18\x03 \x01(\t\"~\n\x12RegisterEventError\x12(\n\ninput_data\x18\x01 \x01(\x0b\x32\x14.kafka.RegisterEvent\x12*\n\rerror_message\x18\x02 \x01(\x0b\x32\x13.kafka.ErrorMessage\x12\x12\n\nerror_type\x18\x03 \x01(\t\"\x1b\n\tErrorList\x12\x0e\n\x06values\x18\x01 \x03(\t\"\xbf\x01\n\x0c\x45rrorMessage\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0e\n\x06status\x18\x03 \x01(\x05\x12\x10\n\x08trace_id\x18\x04 \x01(\t\x12/\n\x06\x65rrors\x18\x05 \x03(\x0b\x32\x1f.kafka.ErrorMessage.ErrorsEntry\x1a?\n\x0b\x45rrorsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x1f\n\x05value\x18\x02 \x01(\x0b\x32\x10.kafka.ErrorList:\x02\x38\x01\x32P\n\x12KafkaStreamService\x12:\n\tSubscribe\x12\x16.google.protobuf.Empty\x1a\x13.kafka.KafkaMessage0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'kafka_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ERRORMESSAGE_ERRORSENTRY']._loaded_options = None
  _globals['_ERRORMESSAGE_ERRORSENTRY']._serialized_options = b'8\001'
  _globals['_KAFKAMESSAGE']._serialized_start=51
  _globals['_KAFKAMESSAGE']._serialized_end=165
  _globals['_REGISTEREVENT']._serialized_start=167
  _globals['_REGISTEREVENT']._serialized_end=230
  _globals['_REGISTEREVENTERROR']._serialized_start=232
  _globals['_REGISTEREVENTERROR']._serialized_end=358
  _globals['_ERRORLIST']._serialized_start=360
  _globals['_ERRORLIST']._serialized_end=387
  _globals['_ERRORMESSAGE']._serialized_start=390
  _globals['_ERRORMESSAGE']._serialized_end=581
  _globals['_ERRORMESSAGE_ERRORSENTRY']._serialized_start=518
  _globals['_ERRORMESSAGE_ERRORSENTRY']._serialized_end=581
  _globals['_KAFKASTREAMSERVICE']._serialized_start=583
  _globals['_KAFKASTREAMSERVICE']._serialized_end=663
# @@protoc_insertion_point(module_scope)
