"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from abc import (
    ABCMeta,
    abstractmethod,
)
from collections.abc import (
    AsyncIterator,
    Iterator,
)
from google.protobuf.empty_pb2 import (
    Empty,
)
from grpc import (
    Channel,
    Server,
    ServicerContext,
    UnaryStreamMultiCallable,
)
from grpc.aio import (
    Channel,
    Server,
    ServicerContext,
    UnaryStreamMultiCallable,
)
from kafka_pb2 import (
    KafkaMessage,
)
from typing import (
    TypeVar,
    Union,
)

_T = TypeVar("_T")

class _MaybeAsyncIterator(AsyncIterator[_T], Iterator[_T], metaclass=ABCMeta): ...

class _ServicerContext(ServicerContext, ServicerContext):  # type: ignore[misc, type-arg]
    ...

class KafkaStreamServiceStub:
    def __init__(self, channel: Union[Channel, Channel]) -> None: ...
    Subscribe: UnaryStreamMultiCallable[
        Empty,
        KafkaMessage,
    ]

class KafkaStreamServiceAsyncStub:
    Subscribe: UnaryStreamMultiCallable[
        Empty,
        KafkaMessage,
    ]

class KafkaStreamServiceServicer(metaclass=ABCMeta):
    @abstractmethod
    def Subscribe(
        self,
        request: Empty,
        context: _ServicerContext,
    ) -> Union[Iterator[KafkaMessage], AsyncIterator[KafkaMessage]]: ...

def add_KafkaStreamServiceServicer_to_server(servicer: KafkaStreamServiceServicer, server: Union[Server, Server]) -> None: ...
