"""
Generated by restcodegen (https://github.com/ValeriyMenshikov/restcodegen).

    source: dm_api_forum
    version: 1.1.1

    Do not edit the class manually.
"""  # noqa: E501
from application.clients.http.dm_api_forum.apis.forum_api import ForumApi

__all__ = [
    "CommentApi",
    "ForumApi",
    "TopicApi",
]